In [11]:
import re
import pandas as pd

In [ ]:
f=open('WhatsAppGroupChat.txt','r', encoding='utf-8') #utf-8 To help Python correctly read emojis and multilingual text

In [15]:
data=f.read()

In [16]:
print(type(data))

<class 'str'>

In [ ]:

pattern = r'\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s' #splitting the wtsap msg between date and msg

In [ ]:
messages= re.split(pattern, data)[1:] #using [1:] to remove the space at the start

In [30]:
dates=re.findall(pattern, data)

In [39]:
#creating pandas dataframe
df = pd.DataFrame({
    'user_message': messages,
    'date': dates
})

In [40]:
#converting the date column 
df['date'] = pd.to_datetime(
    df['date'],
    format='%d/%m/%y, %H:%M - '
)

In [42]:
df.head()

                                        user_message                date
0  Messages and calls are end-to-end encrypted. O... 2026-01-19 20:32:00
1                      Yugratna MUN: 2 wickets 😭😭😭\n 2026-01-19 21:35:00
2                      Yugratna MUN: @⁨Satyam MUN⁩\n 2026-01-19 21:35:00
3         Harsh Mishra MUN: Yugratna mam is best 😋\n 2026-01-19 21:37:00
4                  Harsh Mishra MUN: Satwik mishra\n 2026-01-19 21:37:00

In [44]:
#separating user and msgs
users = []
messages_only = []

for message in df['user_message']:
    entry = re.split(r'([\w\W]+?):\s', message)

    if len(entry) >= 3:
        users.append(entry[1])
        messages_only.append(entry[2])
    else:
        users.append('group_notification')
        messages_only.append(entry[0])
df['user'] = users
df['message'] = messages_only

In [46]:
df.head()

,user_message,date,user,message
0,Messages and calls are end-to-end encrypted. O...,2026-01-19 20:32:00,group_notification,Messages and calls are end-to-end encrypted. O...
1,Yugratna MUN: 2 wickets 😭😭😭\n,2026-01-19 21:35:00,Yugratna MUN,2 wickets 😭😭😭\n
2,Yugratna MUN: @⁨Satyam MUN⁩\n,2026-01-19 21:35:00,Yugratna MUN,@⁨Satyam MUN⁩\n
3,Harsh Mishra MUN: Yugratna mam is best 😋\n,2026-01-19 21:37:00,Harsh Mishra MUN,Yugratna mam is best 😋\n
4,Harsh Mishra MUN: Satwik mishra\n,2026-01-19 21:37:00,Harsh Mishra MUN,Satwik mishra\n

In [54]:
#making columns for year month and date hour min
df['year']=df['date'].dt.year
df['month']=df['date'].dt.month_name()
df['day']=df['date'].dt.day
df['hour']=df['date'].dt.hour
df['minute']=df['date'].dt.minute

In [57]:
df.head()

,user_message,date,user,message,year,month,day,hour,minute
0,Messages and calls are end-to-end encrypted. O...,2026-01-19 20:32:00,group_notification,Messages and calls are end-to-end encrypted. O...,2026,January,19,20,32
1,Yugratna MUN: 2 wickets 😭😭😭\n,2026-01-19 21:35:00,Yugratna MUN,2 wickets 😭😭😭\n,2026,January,19,21,35
2,Yugratna MUN: @⁨Satyam MUN⁩\n,2026-01-19 21:35:00,Yugratna MUN,@⁨Satyam MUN⁩\n,2026,January,19,21,35
3,Harsh Mishra MUN: Yugratna mam is best 😋\n,2026-01-19 21:37:00,Harsh Mishra MUN,Yugratna mam is best 😋\n,2026,January,19,21,37
4,Harsh Mishra MUN: Satwik mishra\n,2026-01-19 21:37:00,Harsh Mishra MUN,Satwik mishra\n,2026,January,19,21,37